mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('docentes/', views.docentes, name='docentes'),
    path('materias/', views.materia, name='materia'),
    path('jornadas/', views.jornadas, name='jornada'),
    path('rol/', views.roles, name='rol'),
    path('grupo/', views.grupos, name='grupo'),
    path('materia_registrar/', views.registrarMateria, name='materia_registrar'),
    path('registrar_docentes/', views.registrarDocente, name='registrar_docentes'),
    path('jornada_registrar/', views.registrarJornadas, name='jornada_registrar'),
    path('rol_registrar/', views.registrarRol, name='rol_registrar'),
    path('grupo_registrar/', views.registrarGrupo, name='grupo_registrar'),
    path('guardar_materia/', views.guardarMateria, name='guardar_materia'),
    path('guardar_docente/', views.guardarDocente, name='guardar_docente'),
    path('guardar_jornada/', views.guardarJornada, name='guardar_jornada'),
    path('guardar_rol/', views.guardarRol, name='guardar_rol'),
    path('guardar_grupo/', views.guardarGrupo, name='guardar_grupo'),
    path('editar_materia/<int:idmateria>', views.editarMateria, name='editar_materia'),
    path('editar_jornada/<int:idjornada>', views.editarJornada, name='editar_jornada'),
    path('editar_rol/<int:idrol>', views.editarRol, name='editar_rol'),
    path('editar_grupo/<int:idgrupo>', views.editarGrupo, name='editar_grupo'),
    path('actualizar_materia/', views.actualizarMateria, name="actualizar_materia"),
    path('actualizar_jornada/', views.actualizarJornada, name="actualizar_jornada"),
    path('actualizar_rol/', views.actualizarRol, name="actualizar_rol"),
    path('actualizar_grupo/', views.actualizarGrupo, name="actualizar_grupo"),
    path('buscar_materia/', views.buscarMateria, name='buscar_materia'),
    path('buscar_jornada/', views.buscarjornada, name='buscar_jornada'),
    path('buscar_rol/', views.buscarRol, name='buscar_rol'),
    path('buscar_grupo/', views.buscarGrupo, name='buscar_grupo'),
    path('eliminar_materia/<int:idmateria>', views.eliminarMateria, name='eliminar_materia'),
    path('eliminar_docente/<int:iddocente>', views.eliminarDocentes, name='eliminar_docente'),
    path('eliminar_jornada/<int:idjornada>', views.eliminarjornada, name='eliminar_jornada'),
    path('eliminar_rol/<int:idrol>', views.eliminarRol, name='eliminar_rol'),
    path('eliminar_grupo/<int:idgrupo>', views.eliminarGrupo, name='eliminar_grupo'),
    
]

polls/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse



from .models import Docentes, Grupos, Jornadas, Materias, Roles

def index(request):
    return render(request, 'polls/index.html')

def docentes(request):
    q = Docentes.objects.all()
    contexto = {'data': q}
    return render(request, 'polls/docentes.html', contexto)

def registrarDocente(request):
    return render(request, 'polls/docentes_registrar.html')


def guardarDocente(request):
    q = Docentes(
        nombre_docente = request.POST["nombre_docente"],
        correo_docente = request.POST["correo_docente"],
        telefono_docente = request.POST["telefono_docente"],
        idmateria = request.POST["idmateria"],
        
    )
    q.save()
    return HttpResponseRedirect(reverse('polls:docentes'))

def eliminarDocentes(request, iddocente):
    #obtener objeto a través de ID
    q = Docentes.objects.get(pk = iddocente)
    q.delete()
    contexto = { 'docente': q.nombre_docente }
    return render(request, 'polls/docentes_eliminar.html', contexto)

def materia(request):
    q = Materias.objects.all()
    contexto = {'data': q}
    return render(request, 'polls/materias.html', contexto)

def registrarMateria(request):
    return render(request, 'polls/materias_registrar.html')

def guardarMateria(request):
    q = Materias(
        nombre_materia = request.POST["nombre_materia"]
        
    )
    q.save()
    return HttpResponseRedirect(reverse('polls:materia'))

def editarMateria(request,idmateria):
    q = Materias.objects.get(pk = idmateria)
    contexto = { 'data': q }
    return render(request, 'polls/materias_editar.html', contexto)

def actualizarMateria(request):
    #Consulto por <<id>> la empresa y obtengo un objeto....
    e = Materias.objects.get(pk = request.POST["idmateria"])

    #actualizo los atributos del objeto, por los que viene del form
    e.nombre_materia = request.POST["nombre_materia"]
    
    
    #actualizamos el objeto en BD.
    e.save()
    return HttpResponseRedirect(reverse('polls:materia'))

def buscarMateria(request):
    q = Materias.objects.filter(nombre_materia__icontains = request.POST["dato"])
    contexto = {'data': q}
    return render(request, 'polls/materias.html', contexto)

def eliminarMateria(request, idmateria):
    #obtener objeto a través de ID
    q = Materias.objects.get(pk = idmateria)
    q.delete()
    contexto = { 'materia': q.nombre_materia }
    return render(request, 'polls/materias_eliminar.html', contexto)

def jornadas(request):
    q = Jornadas.objects.all()
    contexto = {'data': q}
    return render(request, 'polls/jornadas.html', contexto)

def registrarJornadas(request):
    return render(request, 'polls/jornadas_registrar.html')


def guardarJornada(request):
    q = Jornadas(
        nombre_jornada = request.POST["nombre_jornada"]    
    )
    q.save()
    return HttpResponseRedirect(reverse('polls:jornada'))

def eliminarjornada(request, idjornada):
    #obtener objeto a través de ID
    q = Jornadas.objects.get(pk = idjornada)
    q.delete()
    contexto = { 'jornada': q.nombre_jornada }
    return render(request, 'polls/jornadas_eliminar.html', contexto)

def buscarjornada(request):
    q = Jornadas.objects.filter(nombre_jornada__icontains = request.POST["dato"])
    contexto = {'data': q}
    return render(request, 'polls/jornadas.html', contexto)

def editarJornada(request,idjornada):
    q = Jornadas.objects.get(pk = idjornada)
    contexto = { 'data': q }
    return render(request, 'polls/jornadas_editar.html', contexto)

def actualizarJornada(request):
    #Consulto por <<id>> la empresa y obtengo un objeto....
    e = Jornadas.objects.get(pk = request.POST["idjornada"])

    #actualizo los atributos del objeto, por los que viene del form
    e.nombre_jornada = request.POST["nombre_jornada"]
    
    
    #actualizamos el objeto en BD.
    e.save()
    return HttpResponseRedirect(reverse('polls:jornada'))

def roles(request):
    q = Roles.objects.all()
    contexto = {'data': q}
    return render(request, 'polls/roles.html', contexto)

def registrarRol(request):
    return render(request, 'polls/roles_registrar.html')


def guardarRol(request):
    q = Roles(
        nombre_rol = request.POST["nombre_rol"],
        permisos_rol = request.POST["permisos_rol"]     
    )
    q.save()
    return HttpResponseRedirect(reverse('polls:rol'))


def eliminarRol(request, idrol):
    #obtener objeto a través de ID
    q = Roles.objects.get(pk = idrol)
    q.delete()
    contexto = { 'rol': q.nombre_rol }
    return render(request, 'polls/roles_eliminar.html', contexto)

def buscarRol(request):
    q = Roles.objects.filter(nombre_rol__icontains = request.POST["dato"])
    contexto = {'data': q}
    return render(request, 'polls/roles.html', contexto)

def editarRol(request,idrol):
    q = Roles.objects.get(pk = idrol)
    contexto = { 'data': q }
    return render(request, 'polls/roles_editar.html', contexto)

def actualizarRol(request):
    #Consulto por <<id>> la empresa y obtengo un objeto....
    e = Roles.objects.get(pk = request.POST["idrol"])

    #actualizo los atributos del objeto, por los que viene del form
    e.nombre_rol = request.POST["nombre_rol"]
    e.permisos_rol = request.POST["permisos_rol"]
    
    
    #actualizamos el objeto en BD.
    e.save()
    return HttpResponseRedirect(reverse('polls:rol'))

def grupos(request):
    q = Grupos.objects.all()
    contexto = {'data': q}
    return render(request, 'polls/grupos.html', contexto)

def registrarGrupo(request):
    return render(request, 'polls/grupos_registrar.html')


def guardarGrupo(request):
    q = Grupos(
        nombre_grupo = request.POST["nombre_grupo"],
            
    )
    q.save()
    return HttpResponseRedirect(reverse('polls:grupo'))


def eliminarGrupo(request, idgrupo):
    #obtener objeto a través de ID
    q = Grupos.objects.get(pk = idgrupo)
    q.delete()
    contexto = { 'grupo': q.nombre_grupo }
    return render(request, 'polls/grupos_eliminar.html', contexto)

def buscarGrupo(request):
    q = Grupos.objects.filter(nombre_grupo__icontains = request.POST["dato"])
    contexto = {'data': q}
    return render(request, 'polls/grupos.html', contexto)

def editarGrupo(request,idgrupo):
    q = Grupos.objects.get(pk = idgrupo)
    contexto = { 'data': q }
    return render(request, 'polls/grupos_editar.html', contexto)

def actualizarGrupo(request):
    #Consulto por <<id>> la empresa y obtengo un objeto....
    e = Grupos.objects.get(pk = request.POST["idgrupo"])

    #actualizo los atributos del objeto, por los que viene del form
    e.nombre_grupo = request.POST["nombre_grupo"]
    
    
    
    #actualizamos el objeto en BD.
    e.save()
    return HttpResponseRedirect(reverse('polls:grupo'))

polls/templates/polls/grupos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sena - Nómina</title>

    <link href="{% static 'polls/css/estilos.css' %}" rel="stylesheet" />
    <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet" />

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'polls/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'polls/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'polls/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'polls/favicon_io/site.webmanifest' %}">
    <script src="{% static 'polls/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/js/popper.min.js' %}"></script>
    <script src="{% static 'polls/js/libreria.js' %}"></script>
    <script src="{% static 'polls/js/jquery-3.6.0.min.js' %}"></script>

</head>

<body>

    <nav class="navbar dely navbar-expand-lg navbar-dark ">
        <!--color oscuro:bg-dark -->
        <!-- Brand -->
        <a class="navbar-brand px-3" href="{% url 'polls:index' %}"><img class="logo" src="{% static 'polls/img/Logotipo.jpeg' %}" height="70" width="260"></a>

        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link " href="#">
                    Estudiantes
                </a>
                
            </li>
            
                <a class="nav-link " href="{% url 'polls:materia' %}">
                    Materias
                </a>
                
            

            <!-- Dropdown -->
            <li class="nav-item ">
                <a class="nav-link " href="#" >
                    Grupos
                </a>
                
            </li>
            
            <li class="nav-item ">
                <a class="nav-link " href="{% url 'polls:docentes' %}" >
                    Docentes
                </a>

            </li>
                
                
            <li class="nav-item ">
                <a class="nav-link " href="#" >
                    Padre de Familia
                </a>
                
            </li>
           
            
            
        </ul>

      

    </nav>
    
    
    
      </nav>


    <div class="card text-dark bg-light mb-3">
        
        <div class="card-body">
            <h5 class="card-title">Listado de Grupos</h5>


            <div class=" row">

                <div class="col-md-2">
                    <a class="btn btn-success" role="button" href="{% url 'polls:grupo_registrar' %}">Nuevo</a>                </div>
                
                <div class=" container-fluid col-md-6 offset-md-4">
                    <form class="d-flex" action="{% url 'polls:buscar_grupo' %}" method="post" >
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" name="dato" >
                        <button class="btn btn-success col-md-2" type="submit">Buscar</button>
                    </form>
                </div>
                

            </div>
            
            

            <p class="card-text">
                {% if data %}
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        
                        
                        <th colspan="2">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% for i in data %}
                    <tr>
                        
                        <td>{{ i.idgrupo }}</td>
                        <td>{{ i.nombre_grupo }}</td>
                        
                        
                        <td><a href="{% url 'polls:eliminar_grupo' i.idgrupo %}" class="btn btn-warning">Eliminar</a></td>
                        <td><a href="{% url 'polls:editar_grupo' i.idgrupo %}" class="btn btn-info">Editar</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    <li class="page-item disabled">
                        <a class="page-link">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
            {% else %}
            no hay datos
            {% endif %}
            </p>
        </div>
    </div>

polls/templates/polls/jornadas.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sena - Nómina</title>

    <link href="{% static 'polls/css/estilos.css' %}" rel="stylesheet" />
    <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet" />

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'polls/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'polls/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'polls/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'polls/favicon_io/site.webmanifest' %}">
    <script src="{% static 'polls/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/js/popper.min.js' %}"></script>
    <script src="{% static 'polls/js/libreria.js' %}"></script>
    <script src="{% static 'polls/js/jquery-3.6.0.min.js' %}"></script>

</head>

<body>

    <nav class="navbar dely navbar-expand-lg navbar-dark ">
        <!--color oscuro:bg-dark -->
        <!-- Brand -->
        <a class="navbar-brand px-3" href="{% url 'polls:index' %}"><img class="logo" src="{% static 'polls/img/Logotipo.jpeg' %}" height="70" width="260"></a>

        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link " href="#">
                    Estudiantes
                </a>
                
            </li>
            
                <a class="nav-link " href="{% url 'polls:materia' %}">
                    Materias
                </a>
                
            

            <!-- Dropdown -->
            <li class="nav-item ">
                <a class="nav-link " href="#" >
                    Grupos
                </a>
                
            </li>
            
            <li class="nav-item ">
                <a class="nav-link " href="{% url 'polls:docentes' %}" >
                    Docentes
                </a>

            </li>
                
                
            <li class="nav-item ">
                <a class="nav-link " href="#" >
                    Padre de Familia
                </a>
                
            </li>
           
            
            
        </ul>

      

    </nav>
    
    
    
      </nav>


    <div class="card text-dark bg-light mb-3">
        
        <div class="card-body">
            <h5 class="card-title">Listado de Materias</h5>


            <div class=" row">

                <div class="col-md-2">
                    <a class="btn btn-success" role="button" href="{% url 'polls:jornada_registrar' %}">Nuevo</a>                </div>
                
                <div class=" container-fluid col-md-6 offset-md-4">
                    <form class="d-flex" action="{% url 'polls:buscar_jornada' %}" method="post" >
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" name="dato" >
                        <button class="btn btn-success col-md-2" type="submit">Search</button>
                    </form>
                </div>
                

            </div>
            
            

            <p class="card-text">
                {% if data %}
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        
                        <th colspan="2">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% for i in data %}
                    <tr>
                        
                        <td>{{ i.idjornada }}</td>
                        <td>{{ i.nombre_jornada }}</td>
                        
                        <td><a href="{% url 'polls:eliminar_jornada' i.idjornada %}" class="btn btn-warning">Eliminar</a></td>
                        <td><a href="{% url 'polls:editar_jornada' i.idjornada %}" class="btn btn-info">Editar</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    <li class="page-item disabled">
                        <a class="page-link">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
            {% else %}
            no hay datos
            {% endif %}
            </p>
        </div>
    </div>

polls/templates/polls/jornadas_eliminar.html
Jornada <strong>{{ jornada }}</strong> eliminada correctamente
<br>
<a href="{% url 'polls:jornada' %}">
    <button type="button" class="btn btn-dark">Aceptar</button>
</a>

polls/templates/polls/materias.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sena - Nómina</title>

    <link href="{% static 'polls/css/estilos.css' %}" rel="stylesheet" />
    <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet" />

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'polls/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'polls/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'polls/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'polls/favicon_io/site.webmanifest' %}">
    <script src="{% static 'polls/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/js/popper.min.js' %}"></script>
    <script src="{% static 'polls/js/libreria.js' %}"></script>
    <script src="{% static 'polls/js/jquery-3.6.0.min.js' %}"></script>

</head>

<body>

    <nav class="navbar dely navbar-expand-lg navbar-dark ">
        <!--color oscuro:bg-dark -->
        <!-- Brand -->
        <a class="navbar-brand px-3" href="{% url 'polls:index' %}"><img class="logo" src="{% static 'polls/img/Logotipo.jpeg' %}" height="70" width="260"></a>

        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link " href="#">
                    Estudiantes
                </a>
                
            </li>
            
                <a class="nav-link " href="{% url 'polls:materia' %}">
                    Materias
                </a>
                
            

            <!-- Dropdown -->
            <li class="nav-item ">
                <a class="nav-link " href="#" >
                    Grupos
                </a>
                
            </li>
            
            <li class="nav-item ">
                <a class="nav-link " href="{% url 'polls:docentes' %}" >
                    Docentes
                </a>

            </li>
                
                
            <li class="nav-item ">
                <a class="nav-link " href="#" >
                    Padre de Familia
                </a>
                
            </li>
           
            
            
        </ul>

      

    </nav>
    
    
    
      </nav>


    <div class="card text-dark bg-light mb-3">
        
        <div class="card-body">
            <h5 class="card-title">Listado de Materias</h5>


            <div class=" row">

                <div class="col-md-2">
                    <a class="btn btn-success" role="button" href="{% url 'polls:materia_registrar' %}">Nuevo</a>                </div>
                
                <div class=" container-fluid col-md-6 offset-md-4">
                    <form class="d-flex" action="{% url 'polls:buscar_materia' %}" method="post" >
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" name="dato" >
                        <button class="btn btn-success col-md-2" type="submit">Search</button>
                    </form>
                </div>
                

            </div>
            
            

            <p class="card-text">
                {% if data %}
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        
                        <th colspan="2">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% for i in data %}
                    <tr>
                        
                        <td>{{ i.idmateria }}</td>
                        <td>{{ i.nombre_materia }}</td>
                        
                        <td><a href="{% url 'polls:eliminar_materia' i.idmateria %}" class="btn btn-warning">Eliminar</a></td>
                        <td><a href="{% url 'polls:editar_materia' i.idmateria %}" class="btn btn-info">Editar</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    <li class="page-item disabled">
                        <a class="page-link">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
            {% else %}
            no hay datos
            {% endif %}
            </p>
        </div>
    </div>
    

    

polls/templates/polls/materias_eliminar.html
Docente <strong>{{ materia }}</strong> eliminado correctamente
<br>
<a href="{% url 'polls:materia' %}">
    <button type="button" class="btn btn-dark">Aceptar</button>
</a>

polls/templates/polls/roles.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sena - Nómina</title>

    <link href="{% static 'polls/css/estilos.css' %}" rel="stylesheet" />
    <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet" />

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'polls/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'polls/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'polls/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'polls/favicon_io/site.webmanifest' %}">
    <script src="{% static 'polls/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/js/popper.min.js' %}"></script>
    <script src="{% static 'polls/js/libreria.js' %}"></script>
    <script src="{% static 'polls/js/jquery-3.6.0.min.js' %}"></script>

</head>

<body>

    <nav class="navbar dely navbar-expand-lg navbar-dark ">
        <!--color oscuro:bg-dark -->
        <!-- Brand -->
        <a class="navbar-brand px-3" href="{% url 'polls:index' %}"><img class="logo" src="{% static 'polls/img/Logotipo.jpeg' %}" height="70" width="260"></a>

        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link " href="#">
                    Estudiantes
                </a>
                
            </li>
            
                <a class="nav-link " href="{% url 'polls:materia' %}">
                    Materias
                </a>
                
            

            <!-- Dropdown -->
            <li class="nav-item ">
                <a class="nav-link " href="#" >
                    Grupos
                </a>
                
            </li>
            
            <li class="nav-item ">
                <a class="nav-link " href="{% url 'polls:docentes' %}" >
                    Docentes
                </a>

            </li>
                
                
            <li class="nav-item ">
                <a class="nav-link " href="#" >
                    Padre de Familia
                </a>
                
            </li>
           
            
            
        </ul>

      

    </nav>
    
    
    
      </nav>


    <div class="card text-dark bg-light mb-3">
        
        <div class="card-body">
            <h5 class="card-title">Listado de Materias</h5>


            <div class=" row">

                <div class="col-md-2">
                    <a class="btn btn-success" role="button" href="{% url 'polls:rol_registrar' %}">Nuevo</a>                </div>
                
                <div class=" container-fluid col-md-6 offset-md-4">
                    <form class="d-flex" action="{% url 'polls:buscar_rol' %}" method="post" >
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" name="dato" >
                        <button class="btn btn-success col-md-2" type="submit">Buscar</button>
                    </form>
                </div>
                

            </div>
            
            

            <p class="card-text">
                {% if data %}
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Permisos</th>
                        
                        <th colspan="2">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% for i in data %}
                    <tr>
                        
                        <td>{{ i.idrol }}</td>
                        <td>{{ i.nombre_rol }}</td>
                        <td>{{ i.permisos_rol }}</td>
                        
                        <td><a href="{% url 'polls:eliminar_rol' i.idrol %}" class="btn btn-warning">Eliminar</a></td>
                        <td><a href="{% url 'polls:editar_rol' i.idrol %}" class="btn btn-info">Editar</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    <li class="page-item disabled">
                        <a class="page-link">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
            {% else %}
            no hay datos
            {% endif %}
            </p>
        </div>
    </div>

polls/templates/polls/roles_eliminar.html
El rol <strong>{{ rol }}</strong> eliminado correctamente
<br>
<a href="{% url 'polls:rol' %}">
    <button type="button" class="btn btn-dark">Aceptar</button>
</a>